### ISSUE TITLE
Can we use lora in stable-diffusion-ui?

### ISSUE THREAD

**Issue by lztz0022** [easydiffusion/easydiffusion#914] opened 2023-02-20 06:20 UTC
It doesn't work neither I put the lora.safetensors file in **models/lora** nor **models/stable-diffusion/lora**.
Can we use lora in stable-diffusion-ui?

**Comment by JeLuF** [comment] 2023-02-21 10:34
No, there's currently no LORA support

**Comment by lztz0022** [comment] 2023-03-01 14:35
Thank you for your reply.
And thank you for your wonderful work. It's really the easiest way to install and use Stable Diffusion, especially version 2.5.

**Comment by devingfx** [comment] 2023-05-19 14:17
This issue have the answer...
https://github.com/cmdr2/stable-diffusion-ui/issues/1170

**Comment by JeLuF** [comment] 2023-07-14 11:06
Closed as duplicate of #1170

**Closed** 2023-08-29 23:19 UTC
Labels: enhancement
