### ISSUE TITLE
How do I use other upscalers?

### ISSUE THREAD

**Issue by ufuksarp** [easydiffusion/easydiffusion#1394] opened 2023-07-07 21:34 UTC
I wanted to try other upscalers, so I downloaded couple of them like "8x_NMKD-Superscale_150000_G.pth" and put them in _models > realesrgan_ folder, but they won't show up.

**Comment by scorpiomaj27** [comment] 2023-07-11 13:24
I'm not sure about that method, but "Upscayl" is a free application and you can first see how your image looks from ED than before deciding if you want to spend time upscaling.

**Comment by JeLuF** [comment] 2023-07-11 16:00
Custom Upscalers are currently not supported.

Closed as duplicate of #939

**Closed** 2023-08-31 04:49 UTC
Labels: enhancement
