### ISSUE TITLE
.bat file uses curl '>'

### ISSUE THREAD

**Issue by kfsone** [easydiffusion/easydiffusion#663] opened 2022-12-15 22:22 UTC
**Describe the bug**
The setup .bat uses redirection to get curl to output to files, this leads to corruption if the user is not using a stock cmd prompt.

**Additional context**
Use the "--output" argument to specify the file to write to, instead:

```
curl -L -K https://me.cmdr2.org/stable-diffusion-ui/sd-v1-4.ckpt --output sd-v1-4.ckpt
```

this is also significantly faster.

**Comment by JeLuF** [comment] 2022-12-17 00:56
Can you provide an example of a prompt that would cause corruption?

**Comment by kfsone** [comment] 2023-01-28 20:46
Sure:
```
01/28/2023 12:43:00 [C:\temp]
Win|PS> python -c 'open("out.txt", "wb").write(b"a\nb\nc\n")'; dir out.txt

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/28/2023 12:43 PM              6 out.txt

01/28/2023 12:43:02 [C:\temp]
Win|PS> type out.txt >redir.txt ; dir redir.txt

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/28/2023 12:43 PM              9 redir.txt

01/28/2023 12:43:20 [C:\temp]
Win|PS> get-content out.txt >redir.txt ; dir redir.txt

    Directory: C:\temp

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           1/28/2023 12:43 PM              9 redir.txt
```

The extra characters are the '\r's added by the OS implementation of redirection.

I originally stumbled on this trying to deal with an svn migration, and re-using the linux svnadmin dump command caused me grief:

```
svnadmin dump 0 10000 >10k.dump
```

this worked fine on linux, but on Windows the dump file becomes invalid, but the actually output sequence from svnadmin dump was still pure '\n'. It was solely the redirection that caused this. (the solution was to svnadmin dump -F 10k.dump)

🥇 dos, 🥇 ...

**Comment by JeLuF** [comment] 2023-05-05 16:29
> The extra characters are the '\r's added by the OS implementation of redirection.

Sorry for the late response. It's not the OS that's adding the extra carriage return characters, but `type`.

```cmd
> python -c "open('out.txt', 'wb').write(b'a\nb\nc\n')"
> dir out.txt
05/05/2023  18:23                 6 out.txt
> python -m http.server 8000

> curl http://localhost:8000/out.txt > out2.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     6  100     6    0     0    324      0 --:--:-- --:--:-- --:--:--   333

> dir out2.txt
05/05/2023  18:25                 6 out2.txt
```

**Comment by kfsone** [comment] 2023-05-06 19:42
Perhaps there's some contextuality to it, but the sqladmin tool I discovered this thru is platform agnostic basic C stdio, and like curl it simply uses stdout as a default file handle to methods taking a file descrpitor.

```
05/06/2023 12:34:43 [C:\temp\outs]
Win|PS> curl https://www.kfs.org >out.win.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2119    0  2119    0     0   5706      0 --:--:-- --:--:-- --:--:--  5711
05/06/2023 12:34:54 [C:\temp\outs]
Win|PS> wsl curl https://www.kfs.org >out.winlin.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2119    0  2119    0     0   5202      0 --:--:-- --:--:-- --:--:--  5193
05/06/2023 12:35:10 [C:\temp\outs]
Win|PS> wsl
oliver@osmith-pc:/mnt/c/temp/outs$ curl https://www.kfs.org >out.lin.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2119    0  2119    0     0   5278      0 --:--:-- --:--:-- --:--:--  5271
oliver@osmith-pc:/mnt/c/temp/outs$ exit
logout
05/06/2023 12:35:20 [C:\temp\outs]
Win|PS> curl https://www.kfs.org -o out.curl.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2119    0  2119    0     0   5235      0 --:--:-- --:--:-- --:--:--  5245
05/06/2023 12:35:33 [C:\temp\outs]
Win|PS> dir

    Directory: C:\temp\outs

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---            5/6/2023 12:35 PM           2119 out.curl.txt
-a---            5/6/2023 12:35 PM           2119 out.lin.txt
-a---            5/6/2023 12:34 PM           2169 out.win.txt
-a---            5/6/2023 12:35 PM           2169 out.winlin.txt
```

More importantly:

![image](https://user-images.githubusercontent.com/323009/236643625-d6a1a02c-3eb2-40a9-b27a-917e24b12320.png)

```
05/06/2023 12:39:43 [C:\temp\outs]
Win|PS> ipython
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.10.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import glob, os, sys

In [2]: for f in glob.glob('*.txt'):
   ...:     with open(f, 'rb') as fh:
   ...:         eol = "dos" if b'\r' in fh.read() else "unix"
   ...:         print(f"{f:20} {eol}")
   ...:
out.curl.txt         unix
out.lin.txt          unix
out.win.txt          dos
out.winlin.txt       dos
```

**Comment by JeLuF** [comment] 2023-05-07 13:41
Can't reproduce.
```
D:\2.35\dev\xx>curl https://www.kfs.org >out.win.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2119    0  2119    0     0   3049      0 --:--:-- --:--:-- --:--:--  3057

D:\2.35\dev\xx>dir
 Directory of D:\2.35\dev\xx

07/05/2023  15:38    <DIR>          .
07/05/2023  15:38    <DIR>          ..
07/05/2023  15:38             2.119 out.win.txt
```
I don't know what kind of command processor you're using there, but it doesn't seem to be `cmd`.

**Comment by kfsone** [comment] 2023-05-09 23:29
In the examples I'm just using Powershell out of habbit - I do a lot of cross-platform work. However it also happens from a regular old, cmdhost hosted cmd prompt under Windows 10 and Windows 11:

![image](https://github.com/cmdr2/stable-diffusion-ui/assets/323009/f2481fba-0c98-4787-a758-6216b471b3b7)

```
C:\temp\outs>curl --version
curl 8.0.1 (Windows) libcurl/8.0.1 Schannel WinIDN
Release-Date: 2023-03-20
...
```

Aside from prettyfying my powershell prompt, enabling long paths, and turning developer mode on, I run pretty stock installs, Windows not being my primary platform.

**Comment by JeLuF** [comment] 2023-05-10 18:37
https://www.kfs.org is a text/html page, and curl needs to output newlines compliant with the Windows conventions. 
The files EasyDiffusion is downloading aren't text files.

**Comment by kfsone** [comment] 2023-06-20 20:47
It's not curl that's the issue, it's the way DOS implements ">". That's why the solution presented here was to tell curl to write the output directly to a file (-o) instead of using a redirect.

- curl -L -K https://me.cmdr2.org/stable-diffusion-ui/sd-v1-4.ckpt >sd-v1-4.ckpt
+ curl -L -K https://me.cmdr2.org/stable-diffusion-ui/sd-v1-4.ckpt --output sd-v1-4.ckpt

**Comment by cmdr2** [comment] 2023-08-31 06:37
Closing since the .bat file no longer uses curl to download things.

**Closed by cmdr2** 2023-08-31 06:37 UTC
Labels: bug
