### ISSUE TITLE
Save prompt metadata to images by default when downloading.

### ISSUE THREAD

**Issue by Metal079** [easydiffusion/easydiffusion#1391] opened 2023-07-05 21:40 UTC
**Is your feature request related to a problem? Please describe.**
Currently to embed generation info into an image you need to modify the settings to enable auto saving of images and then enable the metadata embedding. Even with the option enabled, if you manually download an image it wont have the metadata.

**Describe the solution you'd like**
Most other image generators automatically embed the generation info into generated images, I think this is a great feature to add that i cant see why it's opt-in for auto-saved images only rather than all downloaded images.

**Describe alternatives you've considered**
Other generators, though none are as user-friendly as this one.

**Additional context**
I run an ai image discord and recently added a bot to allow users to get the generation data of posted images generated on my website or auto1111. Easy Diffusion is very user-friendly to install so its been my go-to to recommend for newcomers to stable diffusion, though unfortunately since the embed behavior isn't default it limits the helpfulness of using the bot to help users with their prompts.

**Comment by ufuksarp** [comment] 2023-07-06 01:08
I vote against this, I feel keeping things optional is the better way of doing things.
However, I think metadata settings for auto-saving should be applied to manual downloads aswell or even better different settings for those.

**Comment by fdwr** [comment] 2023-07-06 20:51
Sounds like a duplicate of original issue 467:

https://github.com/easydiffusion/easydiffusion/issues/467
https://github.com/easydiffusion/easydiffusion/issues/966
https://github.com/easydiffusion/easydiffusion/issues/1081
https://github.com/easydiffusion/easydiffusion/issues/1196

> Even with the option enabled, if you manually download an image it wont have the metadata.

Yeah, I'd love this too, that both manually downloaded images and implicitly (automatically-saved) images include metadata consistently.

**Comment by JeLuF** [comment] 2023-07-11 16:11
Close: Duplicate of #467

**Closed** 2023-08-29 22:31 UTC
Labels: enhancement
