### ISSUE TITLE
how to use loRA

### ISSUE THREAD

**Issue by RandomPollas** [easydiffusion/easydiffusion#816] opened 2023-02-03 06:57 UTC
iv'e been seeing these loRA archives, at [civit.ai](https://civitai.com/models/5014/my-hero-academia-horikoshi-kouhei-style-lora) and i don't know if we can use them with this version

**Comment by lztz0022** [comment] 2023-02-20 06:41
Have you found out how to use loRA in stable-diffusion-ui?

**Comment by JeLuF** [comment] 2023-07-14 11:06
Closed as duplicate of #1170

**Closed by JeLuF** 2023-07-14 11:06 UTC
