### ISSUE TITLE
OSError: [Errno 7] Argument list too long: '/bin/sh' 

### ISSUE THREAD

**Issue by ghazel** [easydiffusion/easydiffusion#1779] opened 2024-05-17 22:38 UTC
macOS, M2

The error does not occur every time, but once it starts happening it happens repeatedly. (The command here is `"sysctl -n machdep.cpu.brand_string"`, which seems unlikely to be the culprit.)

```
15:25:18.376 ERROR AnyIO worker thread Traceback (most recent call last):                                                                                                       device_manager.py:256
  File "/Users/me/easy-diffusion/ui/easydiffusion/device_manager.py", line 248, in get_processor_name                                                                
    return subprocess.check_output(command, shell=True).decode().strip()                                                                                                                             
  File "/Users/me/easy-diffusion/installer_files/env/lib/python3.8/subprocess.py", line 411, in check_output                                                         
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                                                                 
  File "/Users/me/easy-diffusion/installer_files/env/lib/python3.8/subprocess.py", line 489, in run                                                                  
    with Popen(*popenargs, **kwargs) as process:                                                                                                                                                     
  File "/Users/me/easy-diffusion/installer_files/env/lib/python3.8/subprocess.py", line 854, in __init__                                                             
    self._execute_child(args, executable, preexec_fn, close_fds,                                                                                                                                     
  File "/Users/me/easy-diffusion/installer_files/env/lib/python3.8/subprocess.py", line 1702, in _execute_child                                                      
    raise child_exception_type(errno_num, err_msg, err_filename)                                                                                                                                     
OSError: [Errno 7] Argument list too long: '/bin/sh' 
```

**Comment by ghazel** [comment] 2024-06-13 14:23
The problem may be here: https://github.com/easydiffusion/easydiffusion/blob/dea962dc8980ea3ec78b610261d834a95d5decf7/ui/easydiffusion/device_manager.py#L246

Repeated calls to `get_processor_name()` could grow the PATH until exceeds a limit (somewhere).

**Comment by cmdr2** [comment] 2024-06-14 04:08
Hi @ghazel Thanks for reporting this (and finding the root cause). Sorry for the delay in looking into this.

You're absolutely right. Might be better to check if `"/usr/sbin"` isn't present in `PATH` before appending it.

Will push a fix shortly.

**Comment by cmdr2** [comment] 2024-06-14 04:20
Hi @ghazel I've pushed a fix for this - https://github.com/easydiffusion/easydiffusion/commit/a261a2d47dfbd455b3d9005f56dd4806c6df268e

Please feel free to reopen if this is still an issue. Thanks for the report and investigation!

**Closed** 2024-06-14 04:19 UTC
Labels: bug
