### ISSUE TITLE
Textual Inversion support

### ISSUE THREAD

**Issue by Blueblizard** [easydiffusion/easydiffusion#1386] opened 2023-07-02 11:03 UTC
¿Some idea when it will be supported and included in the program GUI? I did a request for it in February. I guess the alternative is using Automatic1111.

**Comment by JeLuF** [comment] 2023-07-02 20:10
Duplicate of #590 => Closed.

There is PR #1362 that implements embedding support.

**Closed by JeLuF** 2023-07-02 20:10 UTC
Labels: enhancement
