### ISSUE TITLE
GPU rendering for rx7900XT and rx7900XTX

### ISSUE THREAD

**Issue by JuKo007** [easydiffusion/easydiffusion#1393] opened 2023-07-06 13:11 UTC
**Is your feature request related to a problem? Please describe.**
When using easydiffusion on Linux with an rx7900XT or rx7900XTX GPU, the GPUs are not detected and the processor is used instead.

**Describe the solution you'd like**
It would be great if  rx7900XT and rx7900XTX GPUs could be used with easydiffusion as well

**Describe alternatives you've considered**
I've tried running it on my CPU (5800X3D) but it was prohibitevely slow

**Additional context**
From my limited understanding this might have to to with rocm support for AMDs latest cards on Linux?

**Comment by JeLuF** [comment] 2023-07-06 16:36
ROCm doesn't support the 7900 so far. There is experimental support for it, as explained in this comment: https://github.com/easydiffusion/easydiffusion/issues/1327#issuecomment-1612252221

Closing as duplicate of #1327

**Closed by JeLuF** 2023-07-06 16:36 UTC
Labels: enhancement
