### ISSUE TITLE
Upscale changes the image and JSON file creates another image

### ISSUE THREAD

**Issue by casualpython** [easydiffusion/easydiffusion#1383] opened 2023-07-01 03:32 UTC
**Describe the bug**
Upscale is not supposed to make a different image, right?
Trying to reproduce the image using the json file will generate another image.

**To Reproduce**
1. Generate 2 images simultaneously (I'm using 2.5.41, clean, just installed)
2. Then click on upscale on any and wait. tadah, new image.
3. Now click in "Use these settings", disable upscale and make it generate another image. It's the upscalled image now regular size, not the original.

If you generate only one per time, it doesn't happen once you upscale. If you disable "Show only"... it'll show the correct pair. Looks like.

**Expected behavior**
I'm pretty sure upscale is supposed to make a upscalled version of the image, not a whole new image...

**Screenshots**
I recorded the issue and uploaded on YouTube. It'll be easier to understand.
https://www.youtube.com/watch?v=_tqGifGmvVs

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 22H2
 - Browser: Opera GX, Brave, Chrome, Firefox, Edge, SRWare Iron
 - Version: all up to date

**Smartphone (please complete the following information):**
 - Device: Galaxy A03
 - OS: Android 13
 - Browser Kiwi
 - Version latest

**Additional context**
Fresh install, happens on any checkpoint I try.
Windows 10 x64 22H2, Ryzen 5 5500, 2x8 GB DDR4 3200 CL16 Kingston Fury Beast, Gigabyte B450M-DS3H V2 (F64), RTX 3060 12GB

**Comment by JeLuF** [comment] 2023-07-02 20:22
This is expected and documented behaviour.

> Note that Ancestral sampler, euler_a, dpm2_a and dpmpp_2s_a are not always deterministic. They can create different images when run in different batch sizes. 

https://github.com/easydiffusion/easydiffusion/wiki/How-to-Use#samplers

The upscaler runs with a batch size of "1", while the original image was created with a batch size of "2".

Closed as duplicate of #337

**Closed by JeLuF** 2023-07-02 20:22 UTC
Labels: bug
