### ISSUE TITLE
LocalHost Refuses to Connect

### ISSUE THREAD

**Issue by GregoryBetsey** [easydiffusion/easydiffusion#543] opened 2022-11-24 23:15 UTC
Hello. I installed all the files however, http://localhost:9000/ can't be reached on my browser (Windows 10: Chrome and Firefox)

![Chrome](https://user-images.githubusercontent.com/40677608/203873271-4b788db5-dfb9-449f-97df-9194a9118edc.JPG)
![Firefox](https://user-images.githubusercontent.com/40677608/203873280-3a7fcead-1fd4-4425-8544-a19f46e0e7cc.JPG)

**Comment by nickdevereaux** [comment] 2022-11-24 23:49
Post the output after you run Start Stable Diffusion UI.cmd

**Comment by GregoryBetsey** [comment] 2022-11-25 20:31
the cmd installs the files to this directory, it doesn't run the application. 
![Capture](https://user-images.githubusercontent.com/40677608/204052769-22ff1c97-e266-4ce3-a882-afe502653e6e.JPG)

**Comment by JeLuF** [comment] 2022-11-28 10:10
If you run the installer, there's a cmd window with all the installation progress. At the end of the installation, this also is running the application. Don't close this window. If you have closed it already, you can run `Start Stable Diffusion UI.cmd` again to start it.

If you still can't access `http://localhost:9000`, this can be due to vpn, proxy or anti-malware tools running on your computer. If you have any of them, you need to configure them to allow access to localhost.

Do you know your PC's local IP address? Can you try to connect to `http://your-ip:9000/`, for example `http://192.168.123.45:9000/`?

**Comment by GregoryBetsey** [comment] 2022-12-02 23:53
Stable Diffusion UI.cmd does not stay open once all the dependencies and packages are installed in C: Is this supposed to happen?

**Comment by Doomotron** [comment] 2023-01-29 14:00
I'm having the same issue. Yesterday it worked as intended, going to localhost:9000 would start the command prompt and run SDUI. But today it just refuses to connect. Using the CMD file just reinstalled the whole thing seemingly and surely mustn't be the way to start it. Is there another way of starting it? Alternatively, I will need some help with firewalls because I have no idea how to set them up properly.

**Comment by JeLuF** [comment] 2023-01-29 14:19
After a system restart, run `Start Stable Diffusion UI.cmd` to start the application. It doesn't do a full installation, it only checks for updates.

**Closed** 2023-08-31 06:44 UTC
